steps:
  - name: node
    entrypoint: npm
    args: [ 'install' ]
  - name: node
    entrypoint: npm
    args: [ 'run', 'build' ]
  - name: gcr.io/project-id/firebase
    args: [ 'deploy', '--project=objex14client', '--only=hosting' ]
