steps:
  - name: node
    entrypoint: npm
    args: [ 'install' ]
  - name: node
    entrypoint: npm
    args: [ 'run', 'build' ]
  - name: alpine
    args: [ 'sh', '-c', 'apk add gettext moreutils ; envsubst < /workspace/build/actuator/info | sponge /workspace/build/actuator/info' ]
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args: [ './deploy.sh' ]

options:
  env:
    - "COMMIT_SHA=$COMMIT_SHA"
    - "REACT_APP_GIT_SHA=$COMMIT_SHA"
    - "SHORT_SHA=$SHORT_SHA"
    - "BRANCH_NAME=$BRANCH_NAME"
