steps:
  - name: node
    entrypoint: npm
    args: [ 'install' ]
  - name: node
    entrypoint: npm
    args: [ 'run', 'build' ]
  - name: alpine
    args: [ 'sh', '-c', 'apk add gettext moreutils ; envsubst < /workspace/build/actuator/info | sponge /workspace/build/actuator/info' ]
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args: [ 'gsutil', '-m', '-h', 'Cache-Control:public,max-age=3600', 'rsync', '-d', '-r', 'build/.', 'gs://citaten.odee.net' ]
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args: [ 'gsutil', 'setmeta', '-h', 'Cache-Control:no-cache, max-age=0', '-h', 'Content-Type:application/json', 'gs://citaten.odee.net/actuator/info' ]

options:
  env:
    - "COMMIT_SHA=$COMMIT_SHA"
    - "REACT_APP_GIT_SHA=$COMMIT_SHA"
    - "SHORT_SHA=$SHORT_SHA"
    - "BRANCH_NAME=$BRANCH_NAME"
